# port
server.port=8080

# name and api
server.servlet.context-path=/${spring.application.name}
spring.application.name=sistventas

# oracle cloud settings
spring.datasource.url=jdbc:oracle:thin:@bodegagemma_medium?TNS_ADMIN=./Wallet/BodegaGemma
spring.datasource.username=BodegaGemma 
spring.datasource.password=Valerius2024
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver